name: Deploy

on:
  workflow_dispatch:

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: "18.192.213.152"
            USER_NAME: "ubuntu"
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 400 private_key
          ssh -o StrictHostKeyChecking=no -i  ubuntu@ec2-18-192-213-152.eu-central-1.compute.amazonaws.com

              # Now we have got the access of EC2 and we will start the deploy.
              sudo su -
              mkdir ghaTestFolder
              exit
          ssh -O exit ubuntu@ec2-18-192-213-152.eu-central-1.compute.amazonaws.com
