name: Deploy
on:
  workflow_dispatch:
jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: "18.192.213.152"
            USER_NAME: "ubuntu"
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
           sudo apt update
           sudo apt install git
           git --version
           git clone https://github.com/mjuhas537/Test.git
           sudo apt-get install nodejs -y
           sudo apt install npm -y
           ls
           echo "node -v"
           node -v
           echo "npm -v"
           npm -v
           cd Test/server
           npm i
           npm run dev  &&
           sudo pm2 stop server.js
          '
           
